### ISSUE TITLE
Update packagist repository url please

### ISSUE THREAD

**Issue by kissmybackend** [etnynl/RefreshTokenBundle#3]
Hi. Update packagist repository url please. This broke some pipeline.

**Comment by ricardodevries** [comment]
Hello. I'm not sure what is happening. Using `etnynl/jwt-refresh-token-bundle` works. Could you try again or paste the error message from the pipeline here?

**Comment by kissmybackend** [comment]
Old URL: https://github.com/etnynl/JWTRefreshTokenBundle.git
New URL: https://github.com/etnynl/RefreshTokenBundle.git

Composer try fetch bundle from old repository URL; You can try this by delete vendor folder (sorry for my english).

`   - Installing etnynl/jwt-refresh-token-bundle (v0.9.3): Cloning 2bd1d5cc72
                                                                                                            
   [RuntimeException]                                                                                       
   Failed to clone https://github.com/etnynl/JWTRefreshTokenBundle.git via https, ssh protocols, aborting.  
                                                                                                            
   - https://github.com/etnynl/JWTRefreshTokenBundle.git                                                    
     Cloning into '/var/www/symfony/vendor/etnynl/jwt-refresh-token-bundle'...                              
     remote: Invalid username or password.                                                                  
     fatal: Authentication failed for 'https://github.com/etnynl/JWTRefreshTokenBundle.git/'                
                                                                                                            
   - git@github.com:etnynl/JWTRefreshTokenBundle.git                                                        
     Cloning into '/var/www/symfony/vendor/etnynl/jwt-refresh-token-bundle'...                              
     error: cannot run ssh: No such file or directory                                                       
     fatal: unable to fork              `

**Comment by kissmybackend** [comment]
Old URL has been cached in symfony.lock, I'm sorry I wasted your time

**Comment by ricardodevries** [comment]
It's alright. Packagist cache may be rough sometimes. Glad it's solved.
